/*
Had dynamic imports caching issue, this file was generated by AI :/ and handle each runtime vite esm / next cjs / bun / node
Needs check side effects as it is registering a global resolver with module.registerHooks(...)
*/

import module, { createRequire } from "node:module";
import process from "node:process";
import type { manifest_module } from "@sleetch/core/compiler";

const native_import = new Function("u", "return import(u)") as (
	u: string,
) => Promise<any>;

let counter = 0;
const next_version = () => `${Date.now()}-${counter++}`;

type vite_like = {
	moduleGraph: { invalidateAll(): void };
	ssrLoadModule(id: string): Promise<Record<string, any>>;
};

const VITE = Symbol.for("sleetch.vite_server");
export const attach_vite = (server: vite_like) => {
	(globalThis as any)[VITE] = server;
};

const PARAM = "fresh";
let hooks_on = false;

const enable_deep_fresh = () => {
	// @ts-expect-error
	if (hooks_on || process.versions.bun || !module.registerHooks) return;
	// @ts-expect-error
	module.registerHooks({
		// @ts-expect-error
		resolve(specifier, context, next) {
			const resolved = next(specifier, context);
			if (!context.parentURL) return resolved;
			if (!resolved.url.startsWith("file:")) return resolved;
			if (resolved.url.includes("/node_modules/")) return resolved;

			const v = new URL(context.parentURL).searchParams.get(PARAM);
			if (!v) return resolved;

			const url = new URL(resolved.url);
			url.searchParams.set(PARAM, v);
			return { ...resolved, url: url.href };
		},
	});
	hooks_on = true;
};

const clear_require_cache = (root: string) => {
	const cache = createRequire(import.meta.url).cache;
	for (const key of Object.keys(cache)) {
		if (key.startsWith(root) && !key.includes("node_modules"))
			delete cache[key];
	}
};

const is_next = () => !!process.env.NEXT_RUNTIME;

const can_native_resolve = () => {
	try {
		return typeof import.meta.resolve === "function";
	} catch {
		return false;
	}
};
export const get_manifest = async ({
	fresh = false,
	root,
}: { fresh?: boolean; root?: string } = {}): Promise<
	manifest_module["default"]
> => {
	const static_manifest = async () =>
		(await import("@sleetch/client/manifest")).default;

	if (!fresh) return static_manifest();

	const vite: vite_like | undefined = (globalThis as any)[VITE];
	if (vite) {
		vite.moduleGraph.invalidateAll();
		return (await vite.ssrLoadModule("@sleetch/client/manifest")).default;
	}

	if (is_next() || !can_native_resolve()) return static_manifest();

	enable_deep_fresh();
	if (root) clear_require_cache(root);

	const v = next_version();
	const url = import.meta.resolve("@sleetch/client/manifest-cache-bust");
	const mod = await native_import(`${url}?${PARAM}=${v}`);
	return mod.create_manifest(v);
};
