// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/:locale": {
    params: {
      "locale": string;
    };
  };
  "/:locale/documentation/*": {
    params: {
      "locale": string;
      "*": string;
    };
  };
  "/llms.txt": {
    params: {};
  };
  "/rss.xml": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/:locale" | "/:locale/documentation/*" | "/llms.txt" | "/rss.xml" | "/sitemap.xml";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/*" | "/:locale" | "/:locale/documentation/*" | "/llms.txt" | "/rss.xml" | "/sitemap.xml";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/$locale/_layout.tsx": {
    id: "routes/$locale/_layout";
    page: "/:locale" | "/:locale/documentation/*";
  };
  "routes/$locale/documentation/$.tsx": {
    id: "routes/$locale/documentation/$";
    page: "/:locale/documentation/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/llms.txt.tsx": {
    id: "routes/llms.txt";
    page: "/llms.txt";
  };
  "routes/rss.xml.tsx": {
    id: "routes/rss.xml";
    page: "/rss.xml";
  };
  "routes/sitemap.xml.tsx": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/_layout": typeof import("./src/app/routes/_layout.tsx");
  "routes/$": typeof import("./src/app/routes/$.tsx");
  "routes/$locale/_layout": typeof import("./src/app/routes/$locale/_layout.tsx");
  "routes/$locale/documentation/$": typeof import("./src/app/routes/$locale/documentation/$.tsx");
  "routes/_index": typeof import("./src/app/routes/_index.tsx");
  "routes/llms.txt": typeof import("./src/app/routes/llms.txt.tsx");
  "routes/rss.xml": typeof import("./src/app/routes/rss.xml.tsx");
  "routes/sitemap.xml": typeof import("./src/app/routes/sitemap.xml.tsx");
};