import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { get_tree } from '@sleetch/server';
import { DocumentationHeader, DocumentationLayout, DocumentationProvider } from '@sleetch/react';
import { path_transformer } from '@/components/client/path-transformer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { tree, language } = await get_tree();
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <DocumentationProvider tree={tree} language={language} path_transformer={path_transformer}>
          <DocumentationLayout>
            <DocumentationHeader />
            {children}
          </DocumentationLayout>
        </DocumentationProvider>
      </body>
    </html>
  );
}
